apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jobsite-ingress
  namespace: jobsite
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: yourdomain.com
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: jobsite-frontend-service
            port:
              number: 80
      - path: /api/?(.*)
        pathType: Prefix
        backend:
          service:
            name: jobsite-backend-service
            port:
              number: 5000
