version: "3.9"

services:
  job-evolution:
    build: .
    container_name: job-evolution
    ports:
      - "8000:8000"
    volumes:
      - ../app:/app
      - ../html:/app/templates
      - ../static:/app/static
    restart: always
